### PR TITLE
fixed bug in for in

### LINKED ISSUE #117: fixing execSyncUtils
ExecSyncUtils has faulty injection protection.

### PR DESCRIPTION
**Pull request by eetupur**
Resolves: #117

### CODE REVIEW

File: src/classes/exec-sync-utils.ts [hunk 1]
```diff
@@ -25,10 +25,11 @@ export const runExecSync = async (command: string, options?: ExecSyncOptionsWith
      * Deny executable, shell, installation, registry and python files,
      * files that are run in a sandbox without checks as well as files with possible malware included
      */
-    for (const ext in fileExtensions) {
+
+    for(const ext of fileExtensions){
       if (command.search(ext) != -1) {
         harmful = true;
-        foundExt = ext;
+        foundExt = ext.toString();
```
Comment (veikkahonkanen) [inline src/classes/exec-sync-utils.ts:32]: Is this necessary? Or can console not log any RegExp types?

Comment (eetupur) [reply src/classes/exec-sync-utils.ts:32]: console can output regExp, foundExt has been designated as string, which can obviously be changed.

**Review by veikkahonkanen — APPROVED** [review]

**Review by veikkahonkanen — APPROVED** [review]

File: src/classes/exec-sync-utils.ts [hunk 2]
```diff
@@ -25,10 +25,11 @@ export const runExecSync = async (command: string, options?: ExecSyncOptionsWith
      * Deny executable, shell, installation, registry and python files,
      * files that are run in a sandbox without checks as well as files with possible malware included
      */
-    for (const ext in fileExtensions) {
+
+    for(const ext of fileExtensions){
```
Comment (anttileppa) [inline src/classes/exec-sync-utils.ts]:
```suggestion
    for (const ext of fileExtensions) {
```

**Review by anttileppa — CHANGES_REQUESTED** [review]
